wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1737283587
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.8.19
      5: 0.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 19
dropout:
  desc: null
  value: 0.2625616404826736
hidden_dim:
  desc: null
  value: 1679
lr:
  desc: null
  value: 0.05216777761352031
momentum:
  desc: null
  value: 0.822684738705728
num_epochs:
  desc: null
  value: 155
num_layers:
  desc: null
  value: 7
opt:
  desc: null
  value: sgd
patience:
  desc: null
  value: 10
t:
  desc: null
  value: 0.01
weight_Clip:
  desc: null
  value: 0.6067970057675494
