wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1737284642
    t:
      1:
      - 1
      - 5
      4: 3.8.19
      5: 0.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 58
dropout:
  desc: null
  value: 0.3567594194973879
hidden_dim:
  desc: null
  value: 749
lr:
  desc: null
  value: 0.07558168040294555
momentum:
  desc: null
  value: 0.8325690919707244
num_epochs:
  desc: null
  value: 125
num_layers:
  desc: null
  value: 1
opt:
  desc: null
  value: sgd
patience:
  desc: null
  value: 10
t:
  desc: null
  value: 0.01
weight_Clip:
  desc: null
  value: 0.7614233219649424
