wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1737283445
    t:
      1:
      - 1
      - 5
      4: 3.8.19
      5: 0.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 51
dropout:
  desc: null
  value: 0.22004122140340415
hidden_dim:
  desc: null
  value: 775
lr:
  desc: null
  value: 0.09344658970008402
momentum:
  desc: null
  value: 0.96119533173368
num_epochs:
  desc: null
  value: 42
num_layers:
  desc: null
  value: 3
opt:
  desc: null
  value: sgd
patience:
  desc: null
  value: 10
t:
  desc: null
  value: 0.1
weight_Clip:
  desc: null
  value: 0.7637466282780491
