wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1737281937
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.8.19
      5: 0.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 60
dropout:
  desc: null
  value: 0.1261975156393084
hidden_dim:
  desc: null
  value: 1268
lr:
  desc: null
  value: 0.06362882496694593
momentum:
  desc: null
  value: 0.943737812262622
num_epochs:
  desc: null
  value: 195
num_layers:
  desc: null
  value: 1
opt:
  desc: null
  value: sgd
patience:
  desc: null
  value: 10
t:
  desc: null
  value: 0.1
weight_Clip:
  desc: null
  value: 0.7569051783769465
