wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1737286829
    t:
      1:
      - 1
      - 5
      4: 3.8.19
      5: 0.12.5
      8:
      - 5
batch_size:
  desc: null
  value: 50
dropout:
  desc: null
  value: 0.19014013459810708
hidden_dim:
  desc: null
  value: 1025
lr:
  desc: null
  value: 0.003129471817069596
momentum:
  desc: null
  value: 0.8206826618107675
num_epochs:
  desc: null
  value: 50
num_layers:
  desc: null
  value: 7
opt:
  desc: null
  value: sgd
patience:
  desc: null
  value: 10
t:
  desc: null
  value: 1
weight_Clip:
  desc: null
  value: 0.7743802514353845
